name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
        - 6379/tcp
    strategy:
      matrix:
        node-version: [14.x]
        redis-version: [5]
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: ${{ matrix.redis-version }}
    - name: Install packages and symlink local dependencies
      run: |
        npm install
        npm run bootstrap
    - name: Run tests and report coverage
      run: |
        npm run coverage:ci
